---
title: "Compile habit"
author: "Paul A. Bloom"
date: "March 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(lme4)
source('helper_functions.R')
```

# Pull in anxiety data

```{r}
load('../../anxiety/anxVars.rda') 
load('../../anxiety/scared.rda')

rcads = dplyr::select(anxVars, name, rcads_raw = rcadsRaw, rcads_t = rcadsT)
```

# pull all the brain measures in 
```{r}
# reactivity fear
reactivity_fear = read.csv('compiled_data/comps_amyg_fear_reactivity_master.csv', stringsAsFactors = FALSE) %>%
  dplyr::select(name, Subject, wave, Block, ageCenter, Age, meanAge, prev_studied, motion, scanner, blockBin,
                fear_reactivity_native = og_native_amyg_bilateral_tstat, 
                fear_reactivity_ho = og_ho_amyg_bilateral_tstat,) %>%
  mutate_at(c('fear_reactivity_ho', 'fear_reactivity_native'), scale, center = FALSE)

# reactivity neutral
reactivity_neutral = read.csv('compiled_data/comps_amyg_neut_reactivity_master.csv', stringsAsFactors = FALSE) %>%
  dplyr::select(name, neut_reactivity_native = og_native_amyg_bilateral_tstat, 
                neut_reactivity_ho = og_ho_amyg_bilateral_tstat) %>%
  mutate_if(is.numeric, scale, center = FALSE)


# reactivity fear > neutral
reactivity_fear_minus_neutral = read.csv('compiled_data/comps_amyg_fear_minus_neut_reactivity_master.csv', stringsAsFactors = FALSE)%>%
  dplyr::select(name, fear_minus_neut_reactivity_native = og_native_amyg_bilateral_tstat, 
                fear_minus_neut_reactivity_ho = og_ho_amyg_bilateral_tstat) %>%
  mutate_if(is.numeric, scale, center = FALSE)


# ppi
ppi = read.csv('compiled_data/comps_amyg_all_contrasts_ppi_master.csv', stringsAsFactors = FALSE) %>%
  dplyr::select(name, contains('vmpfc'), contains('mpfc'), -contains('beta')) %>%
  mutate_if(is.numeric, scale, center = FALSE)


# bsc
bsc = read.csv('compiled_data/comps_amyg_all_contrasts_bsc_master.csv', stringsAsFactors = FALSE) %>%
  dplyr::select(name, contains('vmpfc'), -contains('beta'), -contains('left'), -contains('right')) %>%
  mutate_if(is.numeric, scale, center = FALSE)


# slopes
slopes = read.csv('compiled_data/habit_slopes_master_comps.csv', stringsAsFactors = FALSE) %>%	
  dplyr::select(name, contains('bilateral')) %>%
  mutate_if(is.numeric, scale, center = FALSE)

```

# Bind all together
```{r}
all_brain_sep_anx = plyr::join_all(list(reactivity_fear, reactivity_neutral,reactivity_fear_minus_neutral, 
                                        ppi, bsc, slopes,
                                        rcads, sbMasterLong), by = 'name', type = 'left') 
  


write.csv(all_brain_sep_anx, file = 'compiled_data/all_brain_sep_anx_comps.csv', row.names = FALSE)
```
