---
title: "graph_ppi_similarities"
author: "Paul Bloom"
date: "2/1/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)

df = read_csv('ppi_similarities.csv')

# clean data labels
df_long = df %>%
  pivot_longer(-subid) %>%
  dplyr::mutate(roi = case_when(
    grepl('mpfc1', name) ~ 'mPFC1',
    grepl('mpfc2', name) ~ 'mPFC2',
    grepl('mpfc3', name) ~ 'mPFC3',
    grepl('mpfc_big', name) ~ 'Large vmPFC',
    grepl('whole', name) ~ 'Whole Brain',
  ),
  contrast = case_when(
    grepl('fear', name) & !grepl('neut', name) ~ 'Fear > Baseline',
    grepl('neut', name) & !grepl('fear', name) ~ 'Neutral > Baseline',
    grepl('fear', name) & grepl('neut', name) ~ 'Fear > Neutral'
  ))

# plot image similarities by contrast and comparison
ppi_image_similarities = ggplot(df_long, aes(x = roi, y = value, fill = roi)) +
  geom_hline(yintercept = 0, lty = 2) +
  geom_boxplot() +
  facet_grid(cols = vars(contrast), drop = TRUE, scales = 'free_x') +
  theme_bw() + 
  theme(legend.position ='none') +
  labs(y = 'Voxelwise Image Similarity (r)\nBilateral amygdala gPPI with vs. without deconvolution', x= '') +
  ylim(-1, 1)

# save plot
ggsave(ppi_image_similarities, file = 'figures/ppi_image_similarities.png', height = 4, width = 12)

```