---
title: "Compile PPI"
author: "Paul A. Bloom"
date: "March 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(lme4)
library(corrplot)
source('helper_functions.R')
```

# Read in the data and pull together

Get demographic info in
```{r}
demog = read.csv('../2_motion/motionInfoAllEmotions.csv', stringsAsFactors = FALSE) %>%
  dplyr::filter(., runType == 'fear') %>%
  dplyr::select(., name, Subject, wave, Block, Age, group, gender, meanFdIncluded, censoredTR) %>%
  dplyr::mutate(., meanAge = mean(Age), motion = scale(meanFdIncluded), ageCenter = Age - meanAge) # mean-centered age and scaled motion
```

# PPI with/without deconvolution
```{r}
ppi_deconv = read.csv('../7_ppi_fsl/bilateral_amyg_gppi_afni_style_seed_harvardoxfordsubcortical_bilateralamyg.feat_ppi_roi.csv', stringsAsFactors = FALSE) %>%
  dplyr::select(name, contains('Ppi')) %>%
  mutate_if(is.numeric, na_outliers, num_sds = 3) %>%
  mutate_if(is.numeric, scale, center = FALSE) %>%
  dplyr::select(
    name, 
    fear_deconv_mpfc1_tstat = emotPpi_mPFC_sphere_5mm_tstat,
    fear_deconv_mpfc2_tstat = emotPpi_mPFC_sphere_5mm_anterior_tstat,
    fear_deconv_mpfc3_tstat = emotPpi_mPFC_sphere_5mm_anterior_down_tstat,
    fear_deconv_vmpfc_tstat = emotPpi_vmpfc_trimmed_prob.5_tstat,
    fear_deconv_mpfc1_beta = emotPpi_mPFC_sphere_5mm_cope,
    fear_deconv_mpfc2_beta = emotPpi_mPFC_sphere_5mm_anterior_cope,
    fear_deconv_mpfc3_beta = emotPpi_mPFC_sphere_5mm_anterior_down_cope,
    fear_deconv_vmpfc_beta = emotPpi_vmpfc_trimmed_prob.5_cope,
    neut_deconv_mpfc1_tstat = neutralPpi_mPFC_sphere_5mm_tstat,
    neut_deconv_mpfc2_tstat = neutralPpi_mPFC_sphere_5mm_anterior_tstat,
    neut_deconv_mpfc3_tstat = neutralPpi_mPFC_sphere_5mm_anterior_down_tstat,
    neut_deconv_vmpfc_tstat = neutralPpi_vmpfc_trimmed_prob.5_tstat,
    neut_deconv_mpfc1_beta = neutralPpi_mPFC_sphere_5mm_cope,
    neut_deconv_mpfc2_beta = neutralPpi_mPFC_sphere_5mm_anterior_cope,
    neut_deconv_mpfc3_beta = neutralPpi_mPFC_sphere_5mm_anterior_down_cope,
    neut_deconv_vmpfc_beta = neutralPpi_vmpfc_trimmed_prob.5_cope,
    fear_minus_neut_deconv_mpfc1_tstat = emotMinusNeutralPpi_mPFC_sphere_5mm_tstat,
    fear_minus_neut_deconv_mpfc2_tstat = emotMinusNeutralPpi_mPFC_sphere_5mm_anterior_tstat,
    fear_minus_neut_deconv_mpfc3_tstat = emotMinusNeutralPpi_mPFC_sphere_5mm_anterior_down_tstat,
    fear_minus_neut_deconv_vmpfc_tstat = emotMinusNeutralPpi_vmpfc_trimmed_prob.5_tstat,
    fear_minus_neut_deconv_mpfc1_beta = emotMinusNeutralPpi_mPFC_sphere_5mm_cope,
    fear_minus_neut_deconv_mpfc2_beta = emotMinusNeutralPpi_mPFC_sphere_5mm_anterior_cope,
    fear_minus_neut_deconv_mpfc3_beta = emotMinusNeutralPpi_mPFC_sphere_5mm_anterior_down_cope,
    fear_minus_neut_deconv_vmpfc_beta = emotMinusNeutralPpi_vmpfc_trimmed_prob.5_cope
  )

ppi_no_deconv = read.csv('../7_ppi_fsl/bilateral_amyg_gppi_fsl_style_seed_harvardoxfordsubcortical_bilateralamyg.feat_ppi_roi.csv', stringsAsFactors = FALSE) %>%
  dplyr::select(name, contains('Ppi')) %>%
  mutate_if(is.numeric, na_outliers, num_sds = 3) %>%
  mutate_if(is.numeric, scale, center = FALSE) %>%
  dplyr::select(
    name, 
    fear_no_deconv_mpfc1_tstat = emotPpi_mPFC_sphere_5mm_tstat,
    fear_no_deconv_mpfc2_tstat = emotPpi_mPFC_sphere_5mm_anterior_tstat,
    fear_no_deconv_mpfc3_tstat = emotPpi_mPFC_sphere_5mm_anterior_down_tstat,
    fear_no_deconv_vmpfc_tstat = emotPpi_vmpfc_trimmed_prob.5_tstat,
    fear_no_deconv_mpfc1_beta = emotPpi_mPFC_sphere_5mm_cope,
    fear_no_deconv_mpfc2_beta = emotPpi_mPFC_sphere_5mm_anterior_cope,
    fear_no_deconv_mpfc3_beta = emotPpi_mPFC_sphere_5mm_anterior_down_cope,
    fear_no_deconv_vmpfc_beta = emotPpi_vmpfc_trimmed_prob.5_cope,
    neut_no_deconv_mpfc1_tstat = neutralPpi_mPFC_sphere_5mm_tstat,
    neut_no_deconv_mpfc2_tstat = neutralPpi_mPFC_sphere_5mm_anterior_tstat,
    neut_no_deconv_mpfc3_tstat = neutralPpi_mPFC_sphere_5mm_anterior_down_tstat,
    neut_no_deconv_vmpfc_tstat = neutralPpi_vmpfc_trimmed_prob.5_tstat,
    neut_no_deconv_mpfc1_beta = neutralPpi_mPFC_sphere_5mm_cope,
    neut_no_deconv_mpfc2_beta = neutralPpi_mPFC_sphere_5mm_anterior_cope,
    neut_no_deconv_mpfc3_beta = neutralPpi_mPFC_sphere_5mm_anterior_down_cope,
    neut_no_deconv_vmpfc_beta = neutralPpi_vmpfc_trimmed_prob.5_cope,
    fear_minus_neut_no_deconv_mpfc1_tstat = emotMinusNeutralPpi_mPFC_sphere_5mm_tstat,
    fear_minus_neut_no_deconv_mpfc2_tstat = emotMinusNeutralPpi_mPFC_sphere_5mm_anterior_tstat,
    fear_minus_neut_no_deconv_mpfc3_tstat = emotMinusNeutralPpi_mPFC_sphere_5mm_anterior_down_tstat,
    fear_minus_neut_no_deconv_vmpfc_tstat = emotMinusNeutralPpi_vmpfc_trimmed_prob.5_tstat,
    fear_minus_neut_no_deconv_mpfc1_beta = emotMinusNeutralPpi_mPFC_sphere_5mm_cope,
    fear_minus_neut_no_deconv_mpfc2_beta = emotMinusNeutralPpi_mPFC_sphere_5mm_anterior_cope,
    fear_minus_neut_no_deconv_mpfc3_beta = emotMinusNeutralPpi_mPFC_sphere_5mm_anterior_down_cope,
    fear_minus_neut_no_deconv_vmpfc_beta = emotMinusNeutralPpi_vmpfc_trimmed_prob.5_cope
  )


all_ppi = left_join(ppi_deconv, ppi_no_deconv, by = 'name')
```

# 'Task-independent' connectivity from ppi

```{r}
phys_deconv = read.csv('../7_ppi_fsl/bilateral_amyg_gppi_afni_style_seed_harvardoxfordsubcortical_bilateralamyg.feat_ppi_roi.csv', stringsAsFactors = FALSE) %>%
  dplyr::select(name, contains('Phys')) %>%
  mutate_if(is.numeric, na_outliers, num_sds = 3) %>%
  mutate_if(is.numeric, scale, center = FALSE) %>%
  dplyr::select(name,
    phys_deconv_mpfc1_beta = phys_mPFC_sphere_5mm_cope,
    phys_deconv_mpfc1_tstat = phys_mPFC_sphere_5mm_tstat,
    phys_deconv_mpfc3_beta = phys_mPFC_sphere_5mm_anterior_down_cope,
    phys_deconv_mpfc3_tstat = phys_mPFC_sphere_5mm_anterior_down_tstat,
    phys_deconv_vmpfc_beta  = phys_vmpfc_trimmed_prob.5_cope,
    phys_deconv_vmpfc_tstat = phys_vmpfc_trimmed_prob.5_tstat,
    phys_deconv_mpfc2_beta = phys_mPFC_sphere_5mm_anterior_cope,
    phys_deconv_mpfc2_tstat = phys_mPFC_sphere_5mm_anterior_tstat)


phys_no_deconv = read.csv('../7_ppi_fsl/bilateral_amyg_gppi_fsl_style_seed_harvardoxfordsubcortical_bilateralamyg.feat_ppi_roi.csv', stringsAsFactors = FALSE) %>%
  dplyr::select(name, contains('Phys')) %>%
  mutate_if(is.numeric, na_outliers, num_sds = 3) %>%
  mutate_if(is.numeric, scale, center = FALSE) %>%
  dplyr::select(name,
    phys_no_deconv_mpfc1_beta = phys_mPFC_sphere_5mm_cope,
    phys_no_deconv_mpfc1_tstat = phys_mPFC_sphere_5mm_tstat,
    phys_no_deconv_mpfc3_beta = phys_mPFC_sphere_5mm_anterior_down_cope,
    phys_no_deconv_mpfc3_tstat = phys_mPFC_sphere_5mm_anterior_down_tstat,
    phys_no_deconv_vmpfc_beta  = phys_vmpfc_trimmed_prob.5_cope,
    phys_no_deconv_vmpfc_tstat = phys_vmpfc_trimmed_prob.5_tstat,
    phys_no_deconv_mpfc2_beta = phys_mPFC_sphere_5mm_anterior_cope,
    phys_no_deconv_mpfc2_tstat = phys_mPFC_sphere_5mm_anterior_tstat)


phys_all = dplyr::left_join(phys_deconv, phys_no_deconv, by = 'name')
```

# Check correlations in ppi metrics
```{r}
ppi_cors = cor(dplyr::select(all_ppi, -name), use = 'complete.obs')
pdf('plots/ppi/ppi_metric_correlations.pdf', height = 10, width = 10)
corrplot(ppi_cors, method = 'color')
dev.off()
```

```{r}
orig_subs = read.csv('../4_roi_analysis/guessDG89.csv', stringsAsFactors = FALSE) %>%
  mutate(., prev_studied = 1)
```

# Put PPI together with demographics, write to csv
```{r}
master_ppi = left_join(demog, all_ppi, by = 'name') %>%
  left_join(., orig_subs, by = 'name') %>%
  mutate(scanner = ifelse(wave == 3, '2', '1'),
         blockBin = ifelse(Block == 1, 'first', 'notFirst')) 

master_ppi_comps = dplyr::filter(master_ppi, group != 'PI', group != 'Foster')
phys_comps = left_join(demog, phys_all, by = 'name') %>%
  dplyr::filter(group != 'PI', group != 'Foster')

# write out datafiles (one with everyone, one with just comps)
write.csv(dplyr::select(master_ppi_comps, -contains('neut')), 'compiled_data/comps_amyg_fear_ppi_master.csv', row.names = FALSE)
write.csv(dplyr::select(master_ppi, -contains('neut')), 'compiled_data/everyone_amyg_fear_ppi_master.csv', row.names = FALSE)
write.csv(master_ppi, 'compiled_data/everyone_amyg_all_contrasts_ppi_master.csv', row.names = FALSE)
write.csv(master_ppi_comps, 'compiled_data/comps_amyg_all_contrasts_ppi_master.csv', row.names = FALSE)
write.csv(phys_comps, 'compiled_data/comps_amyg_pfc_gppi_phys_terms.csv', row.names = FALSE)
```

# Simple correlations
```{r}
master_ppi_comps %>% 
  tidyr::gather(., key = 'measure', value = 'ppi', contains('conv')) %>%
  ggplot(., aes(x = Age, y = ppi)) +
  stat_smooth(method = 'lm') +
  facet_wrap('measure')
```
